services:
  app:
    image: ghcr.io/vnt87/puppeteeer-capture:latest
    ports:
      - "7654:3000"
    volumes:
      - ./screenshots:/app/screenshots
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: '1gb'
    environment:
      - NODE_ENV=production
